quotes = [
    '"Frankly, my dear, I don\'t give a damn." — Gone with the Wind (1939)',
    '"I\'m gonna make him an offer he can\'t refuse." — The Godfather (1972)',
    '"Toto, I\'ve a feeling we\'re not in Kansas anymore." — The Wizard of Oz (1939)',
    '"Here\'s looking at you, kid." — Casablanca (1942)',
    '"Go ahead, make my day." — Sudden Impact (1983)',
    '"May the Force be with you." — Star Wars (1977)',
    '"No, I am your father." — The Empire Strikes Back (1980)',
    '"I\'ll be back." — The Terminator (1984)',
    '"You talking to me?" — Taxi Driver (1976)',
    '"E.T. phone home." — E.T. (1982)',
    '"To infinity and beyond!" — Toy Story (1995)',
    '"You can\'t handle the truth!" — A Few Good Men (1992)',
    '"Houston, we have a problem." — Apollo 13 (1995)',
    '"My mama always said life was like a box of chocolates." — Forrest Gump (1994)',
    '"You is kind, you is smart, you is important." — The Help (2011)',
    '"I see dead people." — The Sixth Sense (1999)',
    '"I am the king of the world!" — Titanic (1997)',
    '"You shall not pass!" — The Lord of the Rings (2001)',
    '"My precious." — The Lord of the Rings: The Two Towers (2002)',
    '"Why so serious?" — The Dark Knight (2008)',
    '"I am Iron Man." — Avengers: Endgame (2019)',
    '"Roads? Where we are going we don\'t need roads." — Back to the Future (1985)',
    '"Great Scott!" — Back to the Future (1985)',
    '"I volunteer as tribute." — The Hunger Games (2012)',
    '"Just keep swimming." — Finding Nemo (2003)',
    '"Hasta la vista, baby." — Terminator 2: Judgment Day (1991)',
    '"Nobody puts Baby in a corner." — Dirty Dancing (1987)',
    '"Get busy living, or get busy dying." — The Shawshank Redemption (1994)',
    '"Do or do not. There is no try." — The Empire Strikes Back (1980)',
    '"They may take our lives, but they\'ll never take our freedom!" — Braveheart (1995)',
    '"With great power comes great responsibility." — Spider-Man (2002)',
    '"You had me at hello." — Jerry Maguire (1996)',
    '"We are Groot." — Guardians of the Galaxy (2014)',
    '"Life finds a way." — Jurassic Park (1993)',
    '"You\'re gonna need a bigger boat." — Jaws (1975)',
    '"Keep your friends close, but your enemies closer." — The Godfather Part II (1974)',
    '"I\'m the king of the world!" — Titanic (1997)',
    '"Elementary, my dear Watson." — The Adventures of Sherlock Holmes (1939)',
    '"Carpe diem. Seize the day, boys." — Dead Poets Society (1989)',
    '"I feel the need, the need for speed!" — Top Gun (1986)',
    '"You can\'t sit with us!" — Mean Girls (2004)',
    '"I am inevitable." — Avengers: Endgame (2019)',
    '"To boldly go where no man has gone before." — Star Trek: The Motion Picture (1979)',
    '"It\'s alive!" — Frankenstein (1931)',
    '"You are a toy!" — Toy Story (1995)',
    '"Hakuna Matata." — The Lion King (1994)',
    '"Oh yes, the past can hurt. But the way I see it, you can either run from it or learn from it." — The Lion King (1994)',
    '"Everything the light touches is our kingdom." — The Lion King (1994)',
    '"I drink your milkshake!" — There Will Be Blood (2007)',
    '"After all, tomorrow is another day." — Gone with the Wind (1939)',
]